version: '3.6'
services:
    taynguyen-rawdata1:
        image: ngovanmanh/aws-data-taynguyen:2.0.0
        ports: 
            - 5004:5004
        environment:
            - AWS_CONFIG=/home/config/config_pro1.ini
            - AWS_ENV=pro
        deploy:
            restart_policy:
                condition: on-failure
            replicas: 1
            
        volumes:
            - aws_raw_data:/home/data
            - aws_raw_data_error:/home/data_error
            - aws_raw_log:/home/log
            - aws_raw_config:/home/config
            - aws_raw_timming:/home/timming
            - aws_raw_certification:/home/certification
            - aws_raw_file:/home/files
        networks:
            - aws_system_network
    
    taynguyen-rawdata2:     
        image: ngovanmanh/aws-data-taynguyen:2.0.0  
        ports: 
            - 5005:5004        
        environment:
            - AWS_CONFIG=/home/config/config_pro2.ini
            - AWS_ENV=pro
        deploy:
            restart_policy:
                condition: on-failure
            replicas: 1
        volumes:
            - aws_raw_data:/home/data
            - aws_raw_data_error:/home/data_error
            - aws_raw_log:/home/log
            - aws_raw_config:/home/config
            - aws_raw_timming:/home/timming
            - aws_raw_certification:/home/certification
            - aws_raw_file:/home/files
        networks: 
            - aws_system_network
    
    taynguyen-rawdata3:     
        image: ngovanmanh/aws-data-taynguyen:2.0.0 
        ports: 
            - 5006:5004        
        environment:
            - AWS_CONFIG=/home/config/config_pro3.ini
            - AWS_ENV=pro
        deploy:
            restart_policy:
                condition: on-failure
            replicas: 1
        volumes:
            - aws_raw_data:/home/data
            - aws_raw_data_error:/home/data_error
            - aws_raw_log:/home/log
            - aws_raw_config:/home/config
            - aws_raw_timming:/home/timming
            - aws_raw_certification:/home/certification
            - aws_raw_file:/home/files
        networks: 
            - aws_system_network
            
    taynguyen-rawdata4:     
        image: ngovanmanh/aws-data-taynguyen:2.0.0 
        ports: 
            - 5007:5004        
        environment:
            - AWS_CONFIG=/home/config/config_pro4.ini
            - AWS_ENV=pro
        deploy:
            restart_policy:
                condition: on-failure
            replicas: 1
        volumes:
            - aws_raw_data:/home/data
            - aws_raw_data_error:/home/data_error
            - aws_raw_log:/home/log
            - aws_raw_config:/home/config
            - aws_raw_timming:/home/timming
            - aws_raw_certification:/home/certification
            - aws_raw_file:/home/files
        networks: 
            - aws_system_network

volumes:
  aws_raw_data:
    external: true  
  aws_raw_data_error:
    external: true
  aws_raw_log:
    external: true
  aws_raw_config:
    external: true
  aws_raw_timming:
    external: true
  aws_raw_certification:
    external: true
  aws_raw_file:
    driver: local 
    name: aws_raw_file
    driver_opts:
        type: none
        o: bind
        device: "/opt/aws/raw/files"

networks: 
  aws_system_network:
    external: true